name: mac
on: 
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref'
        required: false
        default: 'master'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
      with:
        ref: "${{ github.event.inputs.ref }}"
    - run: sudo mdutil -i off -a # disable spotlight indexing
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
